### ISSUE TITLE
Can't quantize to int4 and can't compile on RTX2080Ti

### ISSUE THREAD

**Issue by kaizizzzzzz** [pytorch-labs/gpt-fast#124]
I have tried gpt-fast on RTX2080Ti.

I could run using int8 quant and without compilation.

However, it seems can't do the int4 quant and compile on RTX2080Ti.

For int4 quant
It shows:
RuntimeError: CUDA error: named symbol not found
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

For compile, it seems the kernel is compiled to use the bf16 calculation, and RTX2080 can't support bf16 calculation, so it may be the case.

But is it possible to solve the int4 quantization on RXT2080Ti?

**Comment by msaroufim** [comment]
2080 is Turing and that unfortunately does not have int4 support https://en.wikipedia.org/wiki/Turing_(microarchitecture)

I come to this Wikipedia page often to see what's supported where

**Comment by kaizizzzzzz** [comment]
Thx!

**Comment by AghaDurrani** [comment]
Hi @kaizizzzzzz, @msaroufim 

I’m encountering the same issue when using the following function:


`c = torch.ops.aten._weight_int4pack_mm(x, weight_int4pack, groupsize, scales_and_zeros)`
The error message I receive is:


`Expected A.dtype() == at::kBFloat16 to be true, but got false. (Could this error message be improved? If so, please report an enhancement request to PyTorch.)`

I’ve made sure that everything is set to fp16, but the issue persists. I'm running on a V100 GPU and using PyTorch version 2.4.1+cu121.

Any suggestions or advice on how to resolve this would be greatly appreciated.

Thank you!
