### ISSUE TITLE
Int4 perplexity

### ISSUE THREAD

**Issue by SinanAkkoyun** [pytorch-labs/gpt-fast#125]
Hi! How does ppl compare between fp16 and your int4?

**Comment by yanboliang** [comment]
Int4 ```mm``` is a CUDA kernel implement matrix multiplication with reduced precision operations. You can check model's inference performance under different precision, like fp16, int8 and int4. I didn't get what is your major point of comparing fp16 and int4, can you elaborate more?

**Comment by SinanAkkoyun** [comment]
I think I assumed your int4 quants were quantization error aware
