### ISSUE TITLE
int4/int4-gptq support in Mixtral 8x7B

### ISSUE THREAD

**Issue by yanbing-j** [pytorch-labs/gpt-fast#129]
Hi maintainers @yanboliang @Chillee ,

I saw Int8 Weight-Only Quantization is enabled in Mixtral 8x7B. And the next step should be supporting int4 and int4-gptq.

May I know the timeline of enabling int4/int4-gptq support in Mixtral 8x7B? Thanks!

**Comment by yanboliang** [comment]
@yanbing-j I think we need an custom int4 kernel to support it, we don't have very near plan to do that.

**Comment by yanbing-j** [comment]
@yanboliang Does int4 kernel in outside gpt-fast fit for Mixtral 8x7B? https://github.com/pytorch-labs/gpt-fast/blob/main/quantize.py#L398

**Comment by yanboliang** [comment]
@yanbing-j I mean the int4 kernel for ```gather``` + ```gemv```, check the details of ```gather + gemv``` and why it's matters to MoE performance from [this post](https://www.thonking.ai/p/short-supporting-mixtral-in-gpt-fast).

**Comment by yanbing-j** [comment]
Thanks for the comments. @yanboliang
