### ISSUE TITLE
Throughput Benchmark Scripts

### ISSUE THREAD

**Issue by HanGuo97** [pytorch-labs/gpt-fast#173]
Hi, thanks for this amazing library!

Just curious, where can I find the script to produce the benchmarking numbers (e.g., tokens/s, bandwidth) shown in the README?

**Comment by Chillee** [comment]
The instructions provided to run `generate.py` should repro the benchmarking numbers in the README.

**Comment by HanGuo97** [comment]
Ah, I just realized I missed this, thanks for the clarifications!
