### ISSUE TITLE
permute function in `convert_hf_checkpoint.py`

### ISSUE THREAD

**Issue by Sohaib9920** [pytorch-labs/gpt-fast#190]
The `convert_hf_checkpoint.py` replaces `wq`, `wk` and `wv` with single `wqkv`. I am confused about the purpose of `permute` function in the creation of `wqkv`. Current implementation of `wqkv` creation does not give same result as individual projections as tested below:
```python
import torch

dim = 12
n_head = 3
n_local_heads = 3
head_dim = 12 // 3
wq = torch.randn(dim, dim)
wk = torch.randn(dim, dim)
wv = torch.randn(dim, dim)
inputs = torch.randn(10, dim)

def permute(w, n_head):
    return (
        w.view(n_head, 2, head_dim // 2, dim)
        .transpose(1, 2)
        .reshape(head_dim * n_head, dim)
    )

wq_p = permute(wq, n_head)
wk_p = permute(wk, n_local_heads)
wqkv = torch.cat([wq_p, wk_p, wv])  #as implemented at line 112

# projecting separately (as in original llama)
q_o = inputs @ wq.T

# projecting collectively (as in fast-gpt)
kv_size = n_local_heads * head_dim
q_f, k_f, v_f = (inputs @ wqkv.T).split([dim, kv_size, kv_size], dim=-1)

assert (q_o == q_f).all()
```

**Comment by yuanzhedong** [comment]
Hi @Sohaib9920 could you share the reason to permute only k and q? I'm also confused here, thank you!

**Comment by Sohaib9920** [comment]
@yuanzhedong 
Hugging face checkpoints permute the wq and wk of original checkpoints such that if num_heads = 2 and head_dim = 4 then projected q and k using the permuted wq and wk will have embeddings with order [1,3,2,4 , 5,7,6,8] instead of [1,2,3,4 , 5,6,7,8] because hf rotary implementation has embeds per head represented as [all x1 = (1,3) , all x2 = (2,4)]. We need to permute back to the original weights such that embeds of each head are [1,2,3,4] and not [1,3,2,4] as required by original rotary implementation. 

You can get this info from huggingface [docs](https://huggingface.co/docs/transformers/v4.44.0/model_doc/llama) under usage tips which provide `conversion script` in which weights are permuted to get HF weights. So we need to permute back to original weights.

**Comment by yuanzhedong** [comment]
> @yuanzhedong Hugging face checkpoints permute the wq and wk of original checkpoints such that if num_heads = 2 and head_dim = 4 then projected q and k using the permuted wq and wk will have embeddings with order [1,3,2,4 , 5,7,6,8] instead of [1,2,3,4 , 5,6,7,8] because hf rotary implementation has embeds per head represented as [all x1 = (1,3) , all x2 = (2,4)]. We need to permute back to the original weights such that embeds of each head are [1,2,3,4] and not [1,3,2,4] as required by original rotary implementation.
> 
> You can get this info from huggingface [docs](https://huggingface.co/docs/transformers/v4.44.0/model_doc/llama) under usage tips which provide `conversion script` in which weights are permuted to get HF weights. So we need to permute back to original weights.

Thank you! That make a lot of sense now!
