### ISSUE TITLE
The Actual Throughput of int8 Quantization is Significantly Lower than Baseline on A100

### ISSUE THREAD

**Issue by crhcrhcrhcrh** [pytorch-labs/gpt-fast#207]
When I use the Llama 7B model after int8 quantization for inference, my throughput is only around 42 tokens/s, which is far lower than the 155 tokens/s stated in the documentation. Below is my execution environment:

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
PyTorch version: 2.3.1+cu121
CUDA version: 12.1
![image](https://github.com/user-attachments/assets/02ddb23b-cdf7-4347-b3f5-a11cc01d0457)

**Comment by crhcrhcrhcrh** [comment]
The device I am using is the A100.

**Comment by HDCharles** [comment]
these techniques assume that they are being used with compile, set --compile and that should go significantly faster

**Comment by crhcrhcrhcrh** [comment]
> 即使有该`--compile`标志，您仍然需要按照[README.md 说明](https://github.com/pytorch-labs/gpt-fast/blob/main/README.md#installation)中概述的那样[每晚安装 PyTorch](https://pytorch.org/get-started/locally/)。[](https://github.com/pytorch-labs/gpt-fast/blob/main/README.md#installation)
> 
> 以前版本的 PyTorch 无法编译 INT8_MM Triton 内核；相反，它们会编译两个单独的内核：一个用于将 int8 转换为 fp32，另一个用于矩阵乘法。这妨碍了实现最佳性能。
> 
> 我不确定 PyTorch 2.5 是否支持 INT8_MM Triton 内核，但 2.4.1 版本不支持。


Thank you for your reply. Using the method you suggested, my average throughput has reached 158.68 tokens/sec.

**Comment by crhcrhcrhcrh** [comment]
> Even with the `--compile` flag, you need to install [PyTorch nightly](https://pytorch.org/get-started/locally/) as outlined in the [README.md instructions](https://github.com/pytorch-labs/gpt-fast/blob/main/README.md#installation).
> 
> Previous versions of PyTorch cannot compile the INT8_MM Triton kernel; instead, they compile two separate kernels: one for converting int8 to fp32 and another for matrix multiplication. This prevents achieving optimal performance.
> 
> I’m not sure if PyTorch 2.5 supports the INT8_MM Triton kernel, but version 2.4.1 does not.

Thank you for your reply. Using the method you suggested, my average throughput has reached 158.68 tokens/sec.
