### ISSUE TITLE
Can we run gpt-fast from Windows Command Prompt or Powershell?  

### ISSUE THREAD

**Issue by maxloosmu** [pytorch-labs/gpt-fast#45]
For this code:
```
export MODEL_REPO=meta-llama/Llama-2-7b-chat-hf
./scripts/prepare.sh $MODEL_REPO
```

I could change to:
`set MODEL_REPO=meta-llama/Llama-2-7b-chat-hf`

But I'm not sure how to proceed further.  Is there a way to run gpt-fast from Windows Command Prompt or Powershell?  

![Screenshot 2023-12-13 015631](https://github.com/pytorch-labs/gpt-fast/assets/71763812/3f0edb9a-6701-4e91-be90-6039afd18690)

**Comment by Chillee** [comment]
I don't think this repo supports powershell - I would suggest using WSL if you want to run this repo on Windows.

**Comment by maxloosmu** [comment]
@Chillee thanks, but i'm having problems trying to run WSL2 with GPU:

https://github.com/microsoft/WSL/issues/10869

**Comment by Chillee** [comment]
I don't have any plans to support powershell in this repo.
