### ISSUE TITLE
What is `torch.ops.aten._convert_weight_to_int4pack` ?

### ISSUE THREAD

**Issue by vgoklani** [pytorch-labs/gpt-fast#58]
I'm using torch.__version__ = 2.1.0a0+32f93b1

which doesn't have 

    AttributeError: '_OpNamespace' 'aten' object has no attribute '_convert_weight_to_int4pack'

What exactly does this do, and is it defined elsewhere?

Unfortunately upgrading to the latest torch-dev breaks `flash-attention2`

**Comment by yifuwang** [comment]
One possible reason for encountering this issue could be the use of a CPU build. Could you check `torch.cuda.is_available()` just to be sure?

**Comment by vgoklani** [comment]
Thanks for the response:

`torch.cuda.is_available() = True`

No problems training either

**Comment by yifuwang** [comment]
Ah you need the pytorch nightly build for this repo.

**Comment by ZipECHO** [comment]
Have you solved this problem? I got same problem when I quantize llama 7b int4.

**Comment by HDCharles** [comment]
you should use the nightly version of torch or at least the recent 2.2 branch cut
