### ISSUE TITLE
I'm trying to use the meta-llama-7b model on my NVIDIA GeForce GTX 1060 6GB

### ISSUE THREAD

**Issue by MeDott29** [pytorch-labs/gpt-fast#7]
24GB of RAM
was wondering if I had any way of running a smaller version of llama-7b on my system

**Comment by suriya-ganesh** [comment]
Hey @MeDott29 seems to me like, you would need a lot more than 6GB to run llama-7b with decen accuracy. as 6GB is not enough memory to run a 7B model.
even with half precision you need 2 Bytes per parameter x 7B is ~ 14GB.

**Comment by Chillee** [comment]
You could plausibly use int4 quantization in this case.
