### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'mmap'

### ISSUE THREAD

**Issue by yafehlis** [pytorch-labs/gpt-fast#74]
Hi:
I am running the code on AMD GPUs (MI210s) and have encountered some issues with 'mmap'. I cannot find a solution online to resolve it. Several codes have 'mmap=True' which causes lots of issues, and I cannot reproduce the results. Please help! Thanks in advance, Yao Fehlis (AMD)

**Comment by yifuwang** [comment]
Any chance you are using PyTorch <= 2.0 in which the `mmap` option hadn't been introduced? This repo requires the latest nightly PyTorch build.
