### ISSUE TITLE
How is llama-7b trained, what is the verification accuracy?

### ISSUE THREAD

**Issue by frankxyy** [pytorch-labs/gpt-fast#86]
Hi, I am wondering about the training process of the small model and the verification accuracy. As it has large effects on the decoding effectiveness. Thank you!

**Comment by Chillee** [comment]
The specdec results here are just using out of the box llama-7B.

**Comment by frankxyy** [comment]
> The specdec results here are just using out of the box llama-7B.

So is there an average speculative decoding length that can pass the verification process?
