### ISSUE TITLE
`eval.py` uses older version of lm_eval

### ISSUE THREAD

**Issue by nairbv** [pytorch-labs/gpt-fast#89]
`eval.py` uses lm_eval.base.BaseLM which doesn't seem to exist in the latest version of lm_eval. (appears to be from lm_eval version 0.3.0, and seems to have been removed in 0.4.0).

the eval.py could be updated to use the latest version or might want to set an explicit version dependency somewhere.

**Comment by yanboliang** [comment]
This has been fixed by https://github.com/pytorch-labs/gpt-fast/pull/91
