### ISSUE TITLE
pass@1 score extremely low using GPT-fast API

### ISSUE THREAD

**Issue by yafehlis** [pytorch-labs/gpt-fast#94]
Hi:

When I run Phind CodeLlama 34B model (https://huggingface.co/Phind/Phind-CodeLlama-34B-v2) on HumanEval through GPT-fast API, the results give a pass@1 score around 23%. However, the pass@1 score should be above 72%. Could you help me out? 

Thanks and Regards,
Yao Fehlis (yao.fehlis@amd.com)

**Comment by yafehlis** [comment]
@kit1980 @msaroufim @yifuwang @huntzhan Could you please help me? Thanks in advance.

**Comment by S-Yacer** [comment]
can you please share your api code?

**Comment by yafehlis** [comment]
I have figured the issue out. It is due to PyTorch and ROCm versions.
